# AWS Credentials
aws:
  access_key_id: AKIAMOCKAWSKEY0000000000000
  secret_access_key: MockAwsSecretKey000000000000000000000000

# GitHub Token
github:
  token: ghp_m0ckgithubtoken000000000000000

# Stripe Keys
stripe:
  live_key: sk_notareallive_0000000000000000
  test_key: sk_notrealtest_0000000000000000

# Google API Key
google:
  api_key: NotARealGoogleKey000000000000000

# Example keys (should be ignored)
example:
  api_key: YOUR_API_KEY_HERE
  test_key: test_key_1234567890 