# AWS Credentials
aws:
  access_key_id: AKIAIOSFODNN7EXAMPLE
  secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# GitHub Token
github:
  token: ghp_1234567890abcdefghijklmnopqrstuvwxyz

# Stripe Keys
stripe:
  live_key: sk_live_1234567890abcdefghijklmn
  test_key: sk_test_1234567890abcdefghijklmn

# Google API Key
google:
  api_key: AIzaSyA1234567890abcdefghijklmnopqrstuvwxyz

# Example keys (should be ignored)
example:
  api_key: YOUR_API_KEY_HERE
  test_key: test_key_1234567890 