# AWS Credentials
aws:
  access_key_id: AKIA_FAKE_EXAMPLE_KEY_FOR_TESTING
  secret_access_key: wJalrFAKEKEYFORTESTINGEXAMPLEKEY

# GitHub Token
github:
  token: ghp_FAKEGITHUBTOKEN123456789012345

# Stripe Keys
stripe:
  live_key: sk_live_FAKESTRIPEKEY123TESTING
  test_key: sk_test_FAKESTRIPEKEY123TESTING

# Google API Key
google:
  api_key: AIza_FAKE_GOOGLE_API_KEY_TESTING

# Example keys (should be ignored)
example:
  api_key: YOUR_API_KEY_HERE
  test_key: test_key_1234567890 